---
title: "covid-spatial plot"
author: "Hemanth Bangalore"
date: "3/26/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list=ls())
```


```{r}
# load required libraries
library(tidyverse)
library("ggplot2")
theme_set(theme_bw())
library("sf")
library("rnaturalearth")
library("rnaturalearthdata")
library("rnaturalearthhires")
library("readxl")
library("httr")
```

```{r}
# Read the data
covid <- read.csv("~/wkspc/covid19/COVID-19-geographic-disbtribution-worldwide-2020-03-31.csv", header = T)
```

```{r}
# Compute total cases and record it under a separate column
covid <- covid %>%
  group_by(countriesAndTerritories)%>% 
  mutate(total_cases = sum(cases))
```

```{r}
world <- ne_countries(scale = "medium", returnclass = "sf")

# Defining centroid of the counties using st_centroid and combine the co-ordinates
world_points <- st_centroid(world)
world_points <- cbind(world, st_coordinates(st_centroid(world$geometry)))

# Merge the covid data set with worl map data set
covid_df <- merge(world_points, covid, 
                 by.x = "brk_a3", by.y = "countryterritoryCode")
```

```{r}
# Rename X and Y-axis
colnames(covid_df)[colnames(covid_df) == 'X'] <- 'longitude'
colnames(covid_df)[colnames(covid_df) == 'Y'] <- 'latitude'
```


```{r}
# Plot the worldmap with covid cases overlaid on top
ggplot(data = world) +
  geom_sf(fill = "antiquewhite") +
  geom_point(data= covid_df,aes(x=longitude, y=latitude, size = cases), 
             color = "indianred2", alpha = 0.4) +
  xlab("") + ylab("") +
  theme(panel.background = element_rect(fill = "aliceblue"),
        panel.border = element_blank()) +
  scale_size_continuous(range = c(1, 8),
                       breaks = c(250, 500, 750, 1000, 
                                  5000, 10000, 20000, 30000,
                                  40000, 50000, 60000, 70000,
                                  80000, 90000, 100000))
```

```{r}
ggsave("map.pdf")
ggsave("map_web.png", width = 12, height = 12, dpi = "screen")
```